apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: demo-vm-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      application: cnv-demo
  template:
    metadata:
      name: cnv-demo
      labels:
        application: cnv-demo
    spec:
      domain:
        devices:
          interfaces:
          - name: nic0
            model: virtio
            masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: containerdisk
            bootOrder: 1
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            cpu: 256m
            memory: 1G
      networks:
      - name: nic0
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:v0.31.0
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            packages:
              - qemu-guest-agent
              - nginx
            package_update: true
            runcmd:
              - systemctl enable --now qemu-guest-agent
              - systemctl enable --now nginx
        name: cloudinitdisk
